package commands

import (
	"context"
	"fmt"
	"strings"

	queryPlugin "devlog/plugins/query"

	"github.com/urfave/cli/v2"
)

func QueryCommand() *cli.Command {
	return &cli.Command{
		Name:        "query",
		Usage:       "Ask questions about your development history in natural language",
		UsageText:   "devlog query [options] [question]",
		Description: "Uses an LLM to understand your question and query your development history intelligently.\n\n   Examples:\n      devlog query \"What was I working on?\"\n      devlog query \"What files did I change today?\"\n      devlog query \"Show me all git commits from last week\"\n      devlog query \"What errors did I encounter yesterday?\"\n      devlog query \"When did I last work on the auth module?\"",
		ArgsUsage:   "[question]",
		Flags: []cli.Flag{
			&cli.IntFlag{
				Name:    "limit",
				Aliases: []string{"l"},
				Usage:   "Maximum number of results (default: uses plugin config)",
			},
			&cli.BoolFlag{
				Name:    "verbose",
				Aliases: []string{"v"},
				Usage:   "Show the query plan generated by the LLM",
			},
		},
		Action: func(c *cli.Context) error {
			question := "What was I working on?"
			if c.NArg() > 0 {
				question = strings.Join(c.Args().Slice(), " ")
			}

			plugin, cfg, err := queryPlugin.LoadPlugin()
			if err != nil {
				return fmt.Errorf("failed to load query plugin: %w", err)
			}

			maxResults := cfg.MaxResults
			if c.IsSet("limit") {
				maxResults = c.Int("limit")
			}

			ctx := context.Background()
			result, err := plugin.Query(ctx, question, maxResults)
			if err != nil {
				return fmt.Errorf("failed to query: %w", err)
			}

			if c.Bool("verbose") {
				fmt.Println(result.FormatPlan())
				fmt.Println()
			}

			fmt.Println(result.Answer)
			return nil
		},
	}
}
